version: "3"
services:
  counter:
    image: ghcr.io/workingrobot/moe-counter
    restart: unless-stopped
    env_file: counter.env
    ports:
      - "3000:3000"
    healthcheck:
      test:
        ["CMD-SHELL", "wget -q --spider --proxy=off 127.0.0.1:3000 || exit 1"]
